/******************************************************************************
 * @file   main_window.cpp
 * @brief  Main app window implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <bitset>
#include <sys/stat.h>

// Other Library Headers
#include <QMessageBox>      // Qt::Widgets
#include <QSerialPortInfo>  // Qt::SerialPort

// Project Headers
#include "serial_dialog.h"
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Helper Functions
 * !Menu Bar
 * !Main Window
 * !Uncategorized
 */

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget (default: nullptr)
 */
MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent), ui_(new Ui::MainWindow),
      ser_water_(new QSerialPort(this)) {
    ui_->setupUi(this);

    // Check if app is running in Windows Subsystem for Linux (WSL2)
    {
        const char* wsl_path = "/run/WSL";

        struct stat buf {};

        if (stat(wsl_path, &buf) == 0 && S_ISDIR(buf.st_mode)) {
            qWarning()
                << "[WARN] You seem to be running this on WSL2. Please ensure "
                   "you have properly forwarded your USB connections.";
        }
    }

    // Set initial state UI of elements
    ui_->a_debug_mode->setChecked(debug_mode_);

    // Populate the combo box
    ui_->pb_refresh->animateClick();
}

/**
 * @brief Standard destructor.
 */
MainWindow::~MainWindow() {
    if (ser_water_->isOpen()) {
        ser_water_->close();
    }

    delete ui_;
}

//------------------------------------------------------------------------------
// !Helper Functions
//------------------------------------------------------------------------------

namespace {  // local to this file

}  // namespace

//------------------------------------------------------------------------------
// !Menu Bar
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Preferences" menu bar action "Debug Mode".
 *        Toggles debug prinouts for this object and all its children.
 */
void MainWindow::on_a_debug_mode_toggled(bool checked) {
    debug_mode_ = checked;

    if (debug_mode_) {
        qDebug() << "[DEBUG] Debug mode enabled";
    }
}

/**
 * @brief Event handler for "Tools" menu bar action "Serial Dialog (non-Qt)".
 *        Opens a "Serial Device" dialog for selecting a "USB"-type device.
 */
void MainWindow::on_a_serial_dialog_triggered() {
    // Display the "Serial Device" dialog
    SerialDialog w_serial_dialog("USB", debug_mode_);
    w_serial_dialog.setModal(true);
    w_serial_dialog.exec();

    // Only continue if "Connect" was successful
    if (w_serial_dialog.result() != QDialog::Accepted) {
        qWarning() << "[WARN] Failed to connect!";
        return;
    }

    qDebug() << "Selected " << w_serial_dialog.GetDeviceName();

    // TODO: implementation
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

/**
 * @brief Connects to the highlighted serial device upon selection.
 */
void MainWindow::on_cb_serial_name_currentTextChanged(const QString& sel) {
    // Clear the existing Serial object, if it exists
    if (ser_water_->isOpen()) {
        ser_water_->close();
    }

    // Set port options
    ser_water_->setBaudRate(QSerialPort::Baud115200);
    ser_water_->setDataBits(QSerialPort::Data8);
    ser_water_->setParity(QSerialPort::NoParity);
    ser_water_->setStopBits(QSerialPort::OneStop);
    ser_water_->setFlowControl(QSerialPort::NoFlowControl);

    // Only continue if "open" is successful
    if (!ser_water_->open(QIODevice::WriteOnly)) {
        qDebug() << "[ERROR] Failed to open port " << ser_water_->portName()
                 << "\n";
        QMessageBox::critical(this, tr("Error"), ser_water_->errorString());
        return;
    }

    // Enable fluid system controls
    ui_->tb_a_in->setEnabled(true);
    ui_->tb_a_in->setStyleSheet("color: red;");
    ui_->tb_b_in->setEnabled(true);
    ui_->tb_b_in->setStyleSheet("color: red;");
    ui_->tb_a_out->setEnabled(true);
    ui_->tb_a_out->setStyleSheet("color: red;");
    ui_->tb_b_out->setEnabled(true);
    ui_->tb_b_out->setStyleSheet("color: red;");
}

/**
 * @brief Refreshes the list of available serial devices.
 */
void MainWindow::on_pb_refresh_clicked() {
    if (debug_mode_) {
        qDebug() << "[DEBUG] Refreshing available serial ports...";
    }

    // Populate serial device selector combo box
    bool found = false;
    const auto ports = QSerialPortInfo::availablePorts();
    for (const auto& port_info : ports) {
        if (debug_mode_) {
            qDebug() << "[DEBUG] Found SerialPort with following metadata\n";
            qDebug() << "  Port:" << port_info.portName() << "\n"
                     << "  Description:" << port_info.description() << "\n"
                     << "  Manufacturer:" << port_info.manufacturer() << "\n";
        }

        // Populate ComboBox (new items are appended to existing list)
        ui_->cb_serial_name->addItem(port_info.portName());
        found = true;  // only needs to be set once
    }

    if (!found) {
        qWarning() << "[WARN] No serial devices were found!";
    }
}

/**
 * @brief Controls state of A-side fluid input.
 *
 * @note Bit field "0b123":
 *       1: A_IN | 2: B_IN | 3: A_OUT | 4: B_OUT
 */
void MainWindow::on_tb_a_in_clicked() {
    if (ui_->tb_a_in->isChecked()) {
        // Set visual indicator
        ui_->tb_a_in->setStyleSheet("color: green;");

        // Disable opposite button
        current_cmd_ &= 0b1101;  // only zero opposite action's bit
        ui_->tb_a_out->setEnabled(false);
        ui_->tb_a_out->setStyleSheet("color: gray;");

        // Send start command
        current_cmd_ |= 0b1000;
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    } else {
        // Reset visual indicator
        ui_->tb_a_in->setStyleSheet("color: red;");

        // Re-enable opposite button
        ui_->tb_a_out->setEnabled(true);
        ui_->tb_a_out->setStyleSheet("color: red;");

        // Send stop command
        current_cmd_ &= 0b0111;  // only zero this action's bit
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    }

    if (debug_mode_) {
        std::bitset<4> x(current_cmd_);
        qDebug() << "[DEBUG] Sent " << x.to_string('*') << "\n";
    }
}

/**
 * @brief Controls state of B-side fluid input.
 *
 * @note Bit field "0b123":
 *       1: A_IN | 2: B_IN | 3: A_OUT | 4: B_OUT
 */
void MainWindow::on_tb_b_in_clicked() {
    if (ui_->tb_b_in->isChecked()) {
        // Set visual indicator
        ui_->tb_b_in->setStyleSheet("color: green;");

        // Disable opposite button
        current_cmd_ &= 0b1110;  // only zero opposite action's bit
        ui_->tb_b_out->setEnabled(false);
        ui_->tb_b_out->setStyleSheet("color: gray;");

        // Send start command
        current_cmd_ |= 0b0100;
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    } else {
        // Reset visual indicator
        ui_->tb_b_in->setStyleSheet("color: red;");

        // Re-enable opposite button
        ui_->tb_b_out->setEnabled(true);
        ui_->tb_b_out->setStyleSheet("color: red;");

        // Send stop command
        current_cmd_ &= 0b1011;  // only zero this action's bit
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    }

    if (debug_mode_) {
        std::bitset<4> x(current_cmd_);
        qDebug() << "[DEBUG] Sent " << x.to_string('*') << "\n";
    }
}

/**
 * @brief Controls state of A-side fluid output.
 *
 * @note Bit field "0b123":
 *       1: A_IN | 2: B_IN | 3: A_OUT | 4: B_OUT
 */
void MainWindow::on_tb_a_out_clicked() {
    if (ui_->tb_a_out->isChecked()) {
        // Set visual indicator
        ui_->tb_a_out->setStyleSheet("color: green;");

        // Disable opposite button
        current_cmd_ &= 0b0111;  // only zero opposite action's bit
        ui_->tb_a_in->setEnabled(false);
        ui_->tb_a_in->setStyleSheet("color: gray;");

        // Send start command
        current_cmd_ |= 0b0010;
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    } else {
        // Reset visual indicator
        ui_->tb_a_out->setStyleSheet("color: red;");

        // Re-enable opposite button
        ui_->tb_a_in->setEnabled(true);
        ui_->tb_a_in->setStyleSheet("color: red;");

        // Send stop command
        current_cmd_ &= 0b1101;  // only zero this action's bit
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    }

    if (debug_mode_) {
        std::bitset<4> x(current_cmd_);
        qDebug() << "[DEBUG] Sent " << x.to_string('*') << "\n";
    }
}

/**
 * @brief Controls state of B-side fluid output.
 *
 * @note Bit field "0b1234":
 *       1: A_IN | 2: B_IN | 3: A_OUT | 4: B_OUT
 */
void MainWindow::on_tb_b_out_clicked() {
    if (ui_->tb_b_out->isChecked()) {
        // Set visual indicator
        ui_->tb_b_out->setStyleSheet("color: green;");

        // Disable opposite button
        current_cmd_ &= 0b1011;  // only zero opposite action's bit
        ui_->tb_b_in->setEnabled(false);
        ui_->tb_b_in->setStyleSheet("color: gray;");

        // Send start command
        current_cmd_ |= 0b0001;
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    } else {
        // Reset visual indicator
        ui_->tb_b_out->setStyleSheet("color: red;");

        // Re-enable opposite button
        ui_->tb_b_in->setEnabled(true);
        ui_->tb_b_in->setStyleSheet("color: red;");

        // Send stop command
        current_cmd_ &= 0b1110;  // only zero this action's bit
        auto to_write = static_cast<char>(current_cmd_);
        ser_water_->write(&to_write);
    }

    if (debug_mode_) {
        std::bitset<4> x(current_cmd_);
        qDebug() << "[DEBUG] Sent " << x.to_string('*') << "\n";
    }
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
